openapi: 3.0.0
info:
  title: CCMS API
  version: 1.0.0
paths:
  /api/v1/cards/{cardId}/status:
    patch:
      summary: Toggle Freeze/Unblock
  /api/v1/cards/{cardId}/block:
    post:
      summary: Permanent Block & Replace